# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 - master

schedules:
  - cron: "0 3 * * *"  # Runs every day at 3 AM
    displayName: "Daily Coana Vulnerability Analysis"
    branches:
      include:
        - main  # Adjust if needed

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
     npx @coana-tech/cli coana run . \
       --api-key $(COANA_API_KEY) \
       --repo-url https://github.com/$(Build.Repository.Name)
  displayName: 'npm install and build'
  env:
    COANA_API_KEY: $(COANA_API_KEY)
