trigger: none

schedules:
  - cron: "0 3 * * *"  # Runs every day at 3 AM
    displayName: "Daily Coana Vulnerability Analysis"
    branches:
      include:
        # Adjust if needed
        - main
        - master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- checkout: self  # Equivalent to GitHub Actions' checkout

- script: |
     npx @coana-tech/cli run . \
       --api-key $COANA_API_KEY \
       --repo-url https://github.com/$(Build.Repository.Name)
  displayName: 'npm install and build'
  env:
    COANA_API_KEY: $(COANA_API_KEY)
